management:
  endpoint:
    health:
      enabled: true
      show-details: always # details enabled for debugging in dev and test profiles

spring:
  r2dbc:
    url: r2dbc:tc:postgresql:///creator_corner_auth?TC_IMAGE_TAG=15-alpine
    username: postgres
    password: postgres

# Variables needed for application function
jwt:
  duration-hours: 24
  cookie-name: creator_corner
  secret: SALkjfnalskupoi135-09kljalkn$-1234jkjlnlnaljs
